version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly

      labels:
        - "area:tooling"
        - "type:dependencies"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

      labels:
        - "area:security"
        - "type: dependencies"
