name: Language Proposal
description: Propose a change to the Jua language specification.
title: "[LANG]: "
labels:
  - type:proposal
  - area:language

body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should the language evolve in this way?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Detailed Proposal
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: Example Syntax

  - type: textarea
    id: semantics
    attributes:
      label: Semantic Behavior

  - type: textarea
    id: compatibility
    attributes:
      label: Backward Compatibility

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
