name: Markdown Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v18

      - name: Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
